### ISSUE TITLE
Feature request: Properly handle duplicated attributes (in enumerations, classes, associations, profiles...)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#660]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Right now, `Studio` allows users to make duplication mistakes without any sort of warnings because we rely on `engine` to throw compilation errors, however, this does not seem to be the case (but that's a separate issue that we would file on `engine` side). Studio should do some validation when building the graph as well as giving users feedback when they are working in form mode.

### Describe the solution you would like to see implemented

- [ ] Fail graph builder (add tests for this) and show warnings in form mode when encounter:
  - [ ] Class properties with the same name
  - [ ] Enumeration with same values
  - [ ] Association properties with the same name
  - [ ] Profile tags with the same value
  - [ ] Profile stereotypes with the same value

> Note that for the case of class properties, due to class inheritance: this analysis might not be trivial as we have to account for overriding properties - which I suppose we support right now in `Pure`, so perhaps, Studio will only do a dumb check for duplicated properties in the list of a class's own properties

### Describe alternatives you have considered

We should also do this validation in `engine`, we thought this is enough, but UX-wise, this isn't, users should get early feedback

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
I think we can close this as https://github.com/finos/legend-studio/issues/941 is closed with an adequate approach, @gayathrir11's change in  #680 has now been integrated to `strict-mode` introduced in #1540
