### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by akphi**
## Summary

- [x] Properly reveal compilation error for relational property mapping (like what we did for M2M and FlatData)
- [x] temporarily disable grammar roundtrip test for persistence DSL
- [x] fix broken test introduced by #1010 
- [x] revert the workaround introduced in #1162
- [x] Temporarily disable broken `DSL Persistence` grammar roundtrip test
- [x] Temporarily hide `global test runner` from activity bar 

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [x] No testing (please provide an explanation)

### CODE REVIEW

**Review by MauricioUyaguari — DISMISSED** [review]
now this is a minor fix PR :)

**Comment by akphi** [comment]
> now this is a minor fix PR :)

image

**Review by MauricioUyaguari — APPROVED** [review]
